### ISSUE TITLE
Merge into `lattices`

### ISSUE THREAD

**Issue by phadej** [coot/heyting-algebras#3]
As we briefly discussed at HaskellX:

I was doubting whethere there are `Heyting` which isn't categorical. Well, there is: https://github.com/phadej/lattices/pull/77. I have convinced myself that `lattices` should have `Heyting` (and `Boolean`). 

I hope you can relicense `Algebra.Boolean`, `Algebra.Heyting` and `Algebra.Heyting.Layered` with *BSD-3-Clause* so they can be added to `lattices`. (I'll be very happy to have you as co-maintainer as well!)

I'd not add `.Free` modules, but rather migrate them into `free-algebras` package. That way `lattices` can stay relatively small package.

**Comment by coot** [comment]
I am fine with that. Better name would be `free-lattices` where we can put all the free instances. I would like to use my `free-algebra` package to provide free algebra interface (as it's done in this package).

**Comment by phadej** [comment]
I leave `free-lattices` up to you :)

**Comment by coot** [comment]
I changed the license to _bsd 3 clause license_.
